"""adding steps tp procedure

Revision ID: 42fe8445558b
Revises: f842c6ca6068
Create Date: 2022-07-02 17:34:00.136170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42fe8445558b'
down_revision = 'f842c6ca6068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duration_in_seconds', sa.Integer(), nullable=True),
    sa.Column('procedure_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step')
    # ### end Alembic commands ###
