"""adding image url to recipe

Revision ID: ec75c6e5cddc
Revises: 3058a27a234e
Create Date: 2022-04-02 17:29:04.952014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec75c6e5cddc'
down_revision = '3058a27a234e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('recipe', sa.Column('image_identidier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'image_identidier')
    op.drop_column('recipe', 'image_url')
    # ### end Alembic commands ###
