"""adding search vector

Revision ID: f842c6ca6068
Revises: ec75c6e5cddc
Create Date: 2022-04-13 19:05:34.758376

"""
from alembic import op
import sqlalchemy as sa

import  sqlalchemy_utils 

# revision identifiers, used by Alembic.
revision = 'f842c6ca6068'
down_revision = 'ec75c6e5cddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    op.create_index('ix_recipe_search_vector', 'recipe', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipe_search_vector', table_name='recipe', postgresql_using='gin')
    op.drop_column('recipe', 'search_vector')
    # ### end Alembic commands ###
