
general:
  version: 0.0.1

baking:
  repository:  "reubinoff.azurecr.io/reubinoff/baking"
  imageVersion: "latest"

  containerPort: 80
  targetPort: 8080

  livenessProbe:
    path: /healthcheck
    port: 80
  readinessProbe:
    path: /healthcheck
    port: 80

db:
  host: "postgresql"
  username: "postgres"
  password: "secretpassword"
  name: "baking"


postgresql:
  postgresqlPassword: "secretpassword"
  postgresqlDatabase: "baking"
    
