version: "3.7"
services:
  baking-service:
    container_name: baking-service
    build:
      dockerfile: Dockerfile
      context: "./"
    image: "reubinoff/baking:latest"
    ports:
      - "8888:80"
    environment: 
        DB_HOST: mysql
        DB_PASS: sql
        DB_NAME: moshereubinoff
    depends_on: 
      - mysql


  mysql:
    container_name: db
    image: mysql:latest
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: sql
    volumes:
        - my-db:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx


volumes:
    my-db: