[tool.poetry]
name = "baking"
version = "0.1.0"
description = ""
authors = ["Moshe Reubinoff <reubinoff@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
uvicorn = "^0.15.0"
fastapi = "^0.68.1"
SQLAlchemy = "^1.4.23"
pydantic = {extras = ["dotenv"], version = "^1.8.2"}
alembic = "^1.7.3"
PyMySQL = "^1.0.2"
sqlalchemy-filters = "^0.12.0"
cryptography = "^3.4.8"
colorlog = "^6.4.1"
SQLAlchemy-Utils = "^0.37.*"
psycopg2-binary = "^2.9.*"

[tool.poetry.dev-dependencies]
pylint = "^2.11.1"
mypy = "^0.910"
black = {version = "^21.9b0", allow-prereleases = true}
autopep8 = "^1.5.7"
factory-boy = "^3.2.0"
pytest = "^6.2.5"
requests = "^2.26.0"
pytest-cov = "^3.0.0"
hypothesis = "^6.23.3"
schemathesis = "^3.10.1"
nox = "^2021.10.1"
flake8 = "^4.0.1"
nox-poetry = "^0.8.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
