[tool.poetry]
name = "baking"
version = "0.1.0"
description = ""
authors = ["Moshe Reubinoff <reubinoff@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

cryptography = "^3.4.8"
colorlog = "^6.4.1"
psycopg2-binary = "^2.9.3"
python-multipart = "^0.0.5"
fastapi = "^0.85.0"
pydantic =  {extras = ["dotenv"], version = "^1.10.2"}
uvicorn = "^0.18.3"
azure-storage-blob = "^12.13.1"
SQLAlchemy-Utils = "^0.38.3"
SQLAlchemy = "^1.4.44"
SQLAlchemy-Searchable = "^1.4.1"
alembic = "^1.8.1"


[tool.poetry.dev-dependencies]
pylint = "^2.11.1"
mypy = "^0.910"
black = {version = "^21.9b0", allow-prereleases = true}
autopep8 = "^1.5.7"
factory-boy = "^3.2.0"
requests = "^2.26.0"
pytest-cov = "^3.0.0"
hypothesis = "^6.23.3"
schemathesis = "^3.10.1"
nox = "^2021.10.1"
flake8 = "^4.0.1"
nox-poetry = "^0.8.6"
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core>=1.2.*"]
build-backend = "poetry.core.masonry.api"
