apiVersion: v1
kind: Service
metadata:
   name: {{ .Chart.Name }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.web.targetPort }}
      targetPort: {{ .Values.web.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}
