apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  serviceName: "Baking-Service"
  db_host: {{ .Values.db.host | quote }}
  db_port: {{ .Values.db.port | quote }}
  db_user: {{ .Values.db.username | quote }}
  db_pass: {{ .Values.db.password | quote }}
  db_name: {{ .Values.db.name | quote }}
