name: flutter-ci

on:
  push:
    branches: [ develop, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta' or 'master'
      - run: cd flutter_client
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test