name: flutter-ci

on:
  push:
    branches: [ develop, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: test
        run: |
          cd flutter_client
          flutter --version
          flutter pub get
          flutter test

  build-web:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: test
        run: |
          cd flutter_client
          flutter build web


  build-android:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: test
        run: |
          cd flutter_client
          flutter build apk
          flutter build appbundle
          ls -l
          