name: flutter-ci

on:
  push:
    branches: [ develop, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: test
        run: |
          cd flutter_client
          flutter --version
          flutter pub get
          flutter test

  build-web:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: web build
        run: |
          cd flutter_client
          flutter build web


  build-android:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.5.3'
      - name: android build
        run: |
          cd flutter_client
          flutter build apk
          flutter build appbundle
          ls -l

  build-ios:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.5.3'
      - name: android ios
        run: |
          cd flutter_client
          flutter build ios --release --no-codesign
