# This is a basic workflow to help you get started with Actions

name: Python Baking app

on:
  push:
    branches: [ develop ]


jobs:
    test:
        runs-on: ubuntu-latest
        services:
          mysql:
            image: postgres:latest
            env:
              POSTGRES_PASSWORD: rootsql
            ports:
              - "5432:5432"
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5

        env:
          CERT_PATH_CI: crt.pem
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

      
        - uses: actions/setup-python@v2
          with:
            python-version: '3.9' 
        
      

        - name: Install Poetry
          uses: snok/install-poetry@v1

        - name: 'Run Pytests'
          run: |
            cd server
            poetry env use 3.9
            poetry install 
            poetry run python -m pytest -xv --cov=src/baking/routers --cov-fail-under=80 --cov-report html 

    deploy:
        runs-on: ubuntu-latest
        needs: test
        env:
          CERT_PATH_CI: crt.pem
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
       
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
    
        - name: Build And Publish Docker
          run: |
            cd server
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/baking-app:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/baking-app:${{ github.sha }}
        
        - uses: azure/webapps-deploy@v2
          with:
            app-name: 'baking-service'
            images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/baking-app:${{ github.sha }}
            
