# This is a basic workflow to help you get started with Actions

name: Python Baking app

on:
  push:
    branches: [ develop ]


jobs:
    test:
        runs-on: ubuntu-latest
        services:
          mysql:
            image: mysql:latest
            env:
              MYSQL_USER: pytest_db_user
              MYSQL_PASSWORD: sql
              MYSQL_ROOT_PASSWORD: rootsql
            ports:
              - "3306:3306"
            options: >-
              --health-cmd "mysqladmin ping"
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5

        env:
          CERT_PATH_CI: crt.pem
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

      
        - uses: actions/setup-python@v2
          with:
            python-version: '3.9' 
        
        - name: Verify MySQL
          run: | 
            sudo apt-get install -y mysql-client 
            mysql -h 127.0.0.1 -u root -prootsql -e  "GRANT ALL PRIVILEGES ON *.* TO 'pytest_db_user'@'%';"
            mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -u${{ job.services.mysql.env['MYSQL_USER'] }} -p${{ job.services.mysql.env['MYSQL_PASSWORD'] }} -e "SHOW DATABASES"
            mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -u root -p${{ job.services.mysql.env['MYSQL_ROOT_PASSWORD'] }} -e  "GRANT ALL PRIVILEGES ON *.* TO '${{ job.services.mysql.env['MYSQL_USER'] }}'@'%';"
            

        - name: Install Poetry
          uses: snok/install-poetry@v1

        - name: 'Run Pytests'
          run: |
            cd server
            poetry env use 3.9
            poetry install 
            poetry run python -m pytest -vvvxs   

            
    deploy:
        runs-on: ubuntu-latest
        needs: test
        env:
          CERT_PATH_CI: crt.pem
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
       
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
    
        - run: |
            cd server
            echo "${{ secrets.CERT_DATA }}" > ${{ env.CERT_PATH_CI }}
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/baking-app:${{ github.sha }} --build-arg CERT_LOCATION=${{ env.CERT_PATH_CI }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/baking-app:${{ github.sha }}
        
        - uses: azure/webapps-deploy@v2
          with:
            app-name: 'baking-service'
            images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/baking-app:${{ github.sha }}
            
