name: web-ci

on:
  push:
    branches: [ develop, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: test
        run: |
          cd flutter_client
          flutter --version
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze .
          flutter test

 