name: web-ci

on:
  workflow_run:
    workflows: ["flutter-ci"]
    branches: [ develop, main]
    types: 
      - completed
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: release-web
          path: web-server/public/
      - run: |
          ls -l
          ls -l web-server
          ls -l web-server/public